acme_counter_homepage:
    path:     /{item}/{number}
    defaults: { _controller: AcmeCounterBundle:Counter:index }

item:
    path:     /item
    defaults: { _controller: AcmeCounterBundle:Item:index }
