acme_sos:
    resource: "@AcmeSOSBundle/Controller/"
    type:     annotation
    prefix:   /

tracker_pipeline:
    resource: "@trackerPipelineBundle/Controller/"
    type:     annotation
    prefix:   /

